import type { Metadata } from "next"
import { Inter } from "next/font/google"

import "./globals.css"
import MainContainer from "@/layouts/MainContainer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Craftopia",
  description:
    "A platform where artisans and crafters can showcase and sell their handmade productsGenerated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainContainer>{children}</MainContainer>
      </body>
    </html>
  )
}
