import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { getServerSession } from "next-auth"

import "./globals.css"
import MainContainer from "@/layouts/MainContainer"
import Providers from "@/lib/Providers"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Craftopia",
  description:
    "A platform where artisans and crafters can showcase and sell their handmade productsGenerated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>
          <MainContainer>{children}</MainContainer>
        </Providers>
      </body>
    </html>
  )
}
